name: weeb_pos
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.16.0
  easy_debounce: ^2.0.2+1
  google_fonts: ^5.1.0
  go_router: ^10.1.2
  image_picker: ^1.0.4
  equatable: ^2.0.5
  data_table_2: ^2.3.8 
  cloud_firestore: ^4.0.5
  firebase_auth: ^4.1.2
  firebase_core: ^2.2.0
  firebase_storage: ^11.0.5
  dartz: ^0.10.1
  shared_preferences: ^2.0.16
  freezed_annotation: ^2.0.3
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  flutter_dotenv: ^5.0.2
  ionicons: ^0.2.2
  google_sign_in: ^5.4.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  freezed: ^2.0.5

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/img/